spring:
  application:
    name: SpringWebFluxTest
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    properties:
      schema: test
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    schemas: test
    location: filesystem:db/migration
    enabled: true

logging:
  level:
    root: info

